Default: &defaults
  database: bbsYesod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: bbsYesod_test.sqlite3
  <<: *defaults

Staging:
  database: bbsYesod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: bbsYesod_production.sqlite3
  poolsize: 100
  <<: *defaults
